language: cpp

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

branches:
  only:
    - master

env:
  global:
    - RENDERDOC_TRAVIS_BUILD=1 RENDERDOC_CI_BUILD=1
  matrix:
    - CODE_BUILD=1 LINUX_BUILD=1 DOCS_BUILD=0

# only build docs once on linux
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: CODE_BUILD=0 LINUX_BUILD=0 DOCS_BUILD=1

# install dependencies
install:
  - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
#  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main'
#  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - if [[ "$CODE_BUILD" == "1" ]]; then sudo apt-get install --allow-unauthenticated -y -qq libx11-dev mesa-common-dev libgl1-mesa-dev qt5-default libqt5x11extras5-dev libxcb-keysyms1-dev gdb ; fi # clang-format-3.8
  - if [[ "$DOCS_BUILD" == "1" ]]; then sudo pip install --upgrade pip setuptools ; sudo pip install Sphinx sphinx-rtd-theme ; fi
#  - if [[ "$CODE_BUILD" == "1" ]]; then clang-format-3.8 -i -style=file $(find pdblocate/ qrenderdoc/ renderdoc/ renderdoccmd/ renderdocshim/ -type f -regex '.*\(/3rdparty/\|/official/\|resource.h\).*' -prune -o -regex '.*\.\(c\|cpp\|h\)$' -print) ; fi
  - git clean -f
  - git diff --exit-code

script:
  - sh ./hash_version.sh
  - if [[ "$CODE_BUILD" == "1" ]]; then make ; fi
  - if [[ "$DOCS_BUILD" == "1" ]]; then cd docs/ && make html ; fi
